#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# (c) 2018, Ricardo Carrillo Cruz <ricarril@redhat.com>
# (c) 2018, Yanis Guenane <yguenane@redhat.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

---
- name: Create server
  vr_server:
    name: '{{ cloud_server_name }}'
    os: '{{ cloud_server_image }}'
    plan: '{{ cloud_server_flavor }}'
    region: '{{ cloud_server_region }}'
    ssh_key: '{{ cloud_server_sshkey }}'
    firewall_group: '{{ cloud_server_security_group }}'
