---
- name: Create server
  os_server:
    name: '{{ cloud_server_name }}'
    image: '{{ cloud_server_image }}'
    flavor: '{{ cloud_server_flavor }}'
    region_name: '{{ cloud_server_region }}'
    key_name: '{{ cloud_server_sshkey }}'
    security_groups: '{{ cloud_server_security_groups }}'
    network: '{{ cloud_server_network|default(None) }}'
    state: '{{ cloud_server_state|default("present") }}'
